[general]
# import = [ "~/.config/alacritty/themes/themes/citylights.toml" ]
# import = [ "~/.config/alacritty/themes/themes/gruvbox_dark.toml" ]
# import = [ "~/.config/alacritty/themes/themes/nordic.toml" ]
# import = [ "~/.config/alacritty/themes/themes/breeze.toml" ]
import = [ "~/.config/alacritty/themes/themes/catppuccin_mocha.toml" ]
# import = [ "~/.config/alacritty/themes/themes/catppuccin_frappe.toml" ]

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]


[window]
opacity = 0.95
blur = false  # macos or kde wyland

[scrolling]
history = 1000

[font]
size = 12
offset = { x = 0, y = -1 }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

# size = 12
# offset = { x = 0, y = 0 }
# normal = { family = "RobotoMono Nerd Font Mono", style = "Regular" }
# bold = { family = "RobotoMono Nerd Font Mono", style = "Bold" }
# italic = { family = "RobotoMono Nerd Font Mono", style = "Italic" }
# bold_italic = { family = "RobotoMono Nerd Font Mono", style = "Bold Italic" }

# size = 12.5
# offset = { x = 0, y = 0 }
# normal = { family = "Berkeley Mono Variable", style = "Regular" }
# bold = { family = "Berkeley Mono Variable", style = "Bold" }
# italic = { family = "Berkeley Mono Variable", style = "Oblique" }
# bold_italic = { family = "Berkeley Mono Variable", style = "Bold Oblique" }

# size = 12
# offset = { x = 0, y = 0 }
# normal = { family = "VictorMono Nerd Font", style = "regular" }
# bold = { family = "VictorMono Nerd Font", style = "Bold" }
# italic = { family = "VictorMono Nerd Font", style = "Italic" }
# bold_italic = { family = "VictorMono Nerd Fonot", style = "Bold Italic" }

# size = 13.5
# offset = { x = 0, y = 0 }
# normal = { family = "ComicMono Nerd Font", style = "Medium" }
# bold = { family = "ComicMono Nerd Font", style = "Bold" }
# italic = { family = "ComicMono Nerd Font", style = "Oblique" }
# bold_italic = { family = "ComicMono Nerd Font", style = "Bold Italic" }

# size = 13
# offset = { x = 0, y = -1 }
# normal = { family = "ComicShannsMono Nerd Font", style = "Regular" }
# bold = { family = "ComicShannsMono Nerd Font", style = "Bold" }
# italic = { family = "ComicShannsMono Nerd Font", style = "Italic" }
# bold_italic = { family = "ComicShannsMono Nerd Font", style = "Bold Italic" }
